---
- name: Mac Setup
  hosts: 127.0.0.1
  connection: local
  vars:
    brew_cask_apps:
      - alfred
      - google-chrome
      - iterm2
      - visual-studio-code
      - virtualbox
      - vagrant
      - copyq
      - karabiner-elements
      - clipy
      - boostnote
      - bettertouchtool
      - balenaetcher
    brew_packages:
      - ansible
      - git
      - jq
      - nmap
      - terraform
      - rust
      - kotlin
      - fzf
      - fish
      - erlang
      - neovim
      - node
      - readline
      - reattach-to-user-namespace
      - ripgrep
      - sqlite
      - tmux
      - htop
      - ghq
      - peco
    pip_packages:
      - robotframework
      - Jinja2
      - selenium
  tasks:
    - name: Install Homebrew Cask packages
      homebrew_cask:
        name: "{{ brew_cask_apps }}"
        state: present
        greedy: yes
    - name: Install Pip Packages
      pip:
        name: "{{ pip_packages }}"
        executable: pip3
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes    
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
    - name: set fish
      command: chsh -s `which fish`
