---
- name: Mac Setup
  hosts: 127.0.0.1
  connection: local
  vars:
    brew_cask_apps:
      - alfred
      - google-chrome
      - iterm2
      - visual-studio-code
      - virtualbox
      - vagrant
      - karabiner-elements
#      - clipy
#      - boostnote
      - bettertouchtool
      - balenaetcher
      - wireshark
      - diffmerge
#      - alacritty
#      - hyper
      - docker
#      - tableplus
#      - graphql-playground
      - snappy
      - maccy
      - notion
    brew_packages:
      - ansible
      - git
      - jq
      - nmap
      - terraform
      - rust
      - kotlin
      - fzf
      - fish
      - erlang
      - neovim
      - node
      - readline
      - reattach-to-user-namespace
      - ripgrep
      - sqlite
      - tmux
      - htop
      - ghq
      - peco
      - pandoc
      - bat
      - github/gh/gh
      - tig
      - lazygit
      - procs
      - ripgrep
      - fd
      - exa
      - lazydocker
      - pyenv
      - ubuntu/microk8s/microk8s
      - deno
      - haskell-stack
      - graphviz
    pip_packages:
      - robotframework
      - Jinja2
      - selenium
  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes    
#        upgrade_all: yes
    - name: Update Homebrew cask
      homebrew_cask:
        name: "{{ brew_cask_apps }}"
        accept_external_apps: true
        greedy: true
        update_homebrew: yes
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
    - name: Install Homebrew Cask packages
      homebrew_cask:
        name: "{{ brew_cask_apps }}"
        accept_external_apps: true
        greedy: true
        state: present
    - name: Install Pip Packages
      pip:
        name: "{{ pip_packages }}"
        executable: pip3
